In [28]:
import numpy as np
import pandas as pd

In [3]:
data1 = pd.DataFrame(np.ones((6,3),dtype=float),columns=['a','b','c'],index=pd.date_range('6/12/2012',periods=6))

In [9]:
data2 = pd.DataFrame(np.ones((6,3),dtype=float)*2,columns=['a','b','c'],index=pd.date_range('6/13/2012',periods=6))

In [10]:
data1

a  b  c
2012-06-12  1  1  1
2012-06-13  1  1  1
2012-06-14  1  1  1
2012-06-15  1  1  1
2012-06-16  1  1  1
2012-06-17  1  1  1

In [11]:
data2

a  b  c
2012-06-13  2  2  2
2012-06-14  2  2  2
2012-06-15  2  2  2
2012-06-16  2  2  2
2012-06-17  2  2  2
2012-06-18  2  2  2

In [12]:
sliced = pd.concat([data1.ix[:'2012-06-14'],data2.ix['2012-06-15':]])

In [13]:
sliced

a  b  c
2012-06-12  1  1  1
2012-06-13  1  1  1
2012-06-14  1  1  1
2012-06-15  2  2  2
2012-06-16  2  2  2
2012-06-17  2  2  2
2012-06-18  2  2  2

In [19]:
data2 = pd.DataFrame(np.ones((6,4),dtype=float)*2,columns=['a','b','c','d'],index=pd.date_range('6/13/2012',periods=6))

In [20]:
sliced = pd.concat([data1.ix[:'2012-06-14'],data2.ix['2012-06-15':]])

In [21]:
sliced

a  b  c   d
2012-06-12  1  1  1 NaN
2012-06-13  1  1  1 NaN
2012-06-14  1  1  1 NaN
2012-06-15  2  2  2   2
2012-06-16  2  2  2   2
2012-06-17  2  2  2   2
2012-06-18  2  2  2   2

In [22]:
sliced.combine_first(data2)

a  b  c   d
2012-06-12  1  1  1 NaN
2012-06-13  1  1  1   2
2012-06-14  1  1  1   2
2012-06-15  2  2  2   2
2012-06-16  2  2  2   2
2012-06-17  2  2  2   2
2012-06-18  2  2  2   2

In [23]:
cp_sliced =sliced.copy()

In [25]:
cp_sliced[['a','c']] = data1[['a','c']]

In [26]:
cp_sliced

a  b   c   d
2012-06-12   1  1   1 NaN
2012-06-13   1  1   1 NaN
2012-06-14   1  1   1 NaN
2012-06-15   1  2   1   2
2012-06-16   1  2   1   2
2012-06-17   1  2   1   2
2012-06-18 NaN  2 NaN   2

In [2]:
import pandas_datareader.data as web

In [6]:
price = web.get_data_yahoo('AAPL','2011-01-01')['Adj Close']

In [8]:
price[-5:]

Date
2018-09-11    223.850006
2018-09-12    221.070007
2018-09-13    226.410004
2018-09-14    223.839996
2018-09-17    217.880005
Name: Adj Close, dtype: float64

In [9]:
price['2011-10-03']/price['2011-3-01'] - 1

0.072399971363090954

In [10]:
returns = price.pct_change()

/usr/local/lib/python2.7/dist-packages/pandas/core/computation/check.py:17: UserWarning: The installed version of numexpr 2.4.3 is not supported in pandas and will be not be used
The minimum supported version is 2.4.6

  ver=ver, min_ver=_MIN_NUMEXPR_VERSION), UserWarning)


In [14]:
ret_index = (1+returns).cumprod()
ret_index[0] = 1

In [16]:
ret_index[:5]

Date
2010-12-31    1.000000
2011-01-03    1.021732
2011-01-04    1.027064
2011-01-05    1.035466
2011-01-06    1.034629
Name: Adj Close, dtype: float64

In [24]:
m_returns = ret_index.resample('BM').last().pct_change()

In [26]:
m_returns['2012']

Date
2012-01-31    0.127111
2012-02-29    0.188311
2012-03-30    0.105283
2012-04-30   -0.025969
2012-05-31   -0.010703
2012-06-29    0.010853
2012-07-31    0.045822
2012-08-31    0.093877
2012-09-28    0.002796
2012-10-31   -0.107600
2012-11-30   -0.012375
2012-12-31   -0.090743
Freq: BM, Name: Adj Close, dtype: float64

In [31]:
np.int32.mro()

[numpy.int32,
 numpy.signedinteger,
 numpy.integer,
 numpy.number,
 numpy.generic,
 object]

In [36]:
arr = np.arange(15)

In [38]:
a = arr.reshape(5,-1)
#-1是让系统自动识别分行的列数

In [39]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [41]:
b = a.ravel()

In [43]:
a.flatten()#扁平化

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
arr = np.arange(3)

In [45]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [52]:
arr = np.arange(10)*100

In [53]:
inds = [7,1,2,6]

In [54]:
arr[inds]

array([700, 100, 200, 600])

In [56]:
arr.take(inds)

array([700, 100, 200, 600])

In [57]:
arr.put(inds,[41,42,43,44])

In [58]:
arr

array([  0,  42,  43, 300, 400, 500,  44,  41, 800, 900])

In [59]:
a = np.array([1,2,3])

In [60]:
a.shape

(3,)